/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#444933",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#910030",
        "surface": "#0f131d",
        "secondary": "#ffb2ba",
        "on-tertiary-fixed": "#002022",
        "tertiary-fixed": "#7df4ff",
        "on-secondary-container": "#ffe6e8",
        "surface-container-high": "#262a35",
        "surface-variant": "#313540",
        "primary": "#ffffff",
        "surface-tint": "#abd600",
        "surface-container": "#1c1f2a",
        "tertiary-fixed-dim": "#00dbe9",
        "surface-dim": "#0f131d",
        "surface-container-lowest": "#0a0e18",
        "on-primary": "#283500",
        "inverse-surface": "#dfe2f1",
        "tertiary-container": "#7df4ff",
        "tertiary": "#ffffff",
        "on-background": "#dfe2f1",
        "on-surface-variant": "#c4c9ac",
        "secondary-fixed": "#ffd9dc",
        "inverse-primary": "#506600",
        "secondary-fixed-dim": "#ffb2ba",
        "on-secondary-fixed": "#400011",
        "on-primary-fixed": "#161e00",
        "on-secondary": "#670020",
        "on-tertiary-container": "#006f77",
        "inverse-on-surface": "#2c303b",
        "on-primary-container": "#556d00",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#3c4d00",
        "on-surface": "#dfe2f1",
        "surface-container-highest": "#313540",
        "error-container": "#93000a",
        "secondary-container": "#d4004b",
        "error": "#ffb4ab",
        "surface-bright": "#353944",
        "primary-fixed-dim": "#abd600",
        "background": "#0f131d",
        "primary-fixed": "#c3f400",
        "outline": "#8e9379",
        "primary-container": "#c3f400",
        "surface-container-low": "#171b26",
        "on-tertiary-fixed-variant": "#004f54",
        "on-tertiary": "#00363a",
        "brand-volt": "#ccff00",
        "brand-volt-dark": "#b0dd00",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "space-3xs": "0.125rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "margin-mobile": "1rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
      },
      fontFamily: {
        "headline-xl-mobile": ["Barlow Condensed", "sans-serif"],
        "headline-md": ["Barlow Condensed", "sans-serif"],
        "display-hero-mobile": ["Barlow Condensed", "sans-serif"],
        "title-base": ["Chivo", "sans-serif"],
        "headline-lg": ["Barlow Condensed", "sans-serif"],
        "body-md": ["Chivo", "sans-serif"],
        "headline-xl": ["Barlow Condensed", "sans-serif"],
        "body-lg": ["Chivo", "sans-serif"],
        "display-hero": ["Barlow Condensed", "sans-serif"],
        "label-sm": ["Chivo", "sans-serif"],
        "body-sm": ["Chivo", "sans-serif"],
        "label-caps": ["Barlow Condensed", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["72px", { lineHeight: "76px", letterSpacing: "0.02em", fontWeight: "800" }],
        "headline-xl": ["48px", { lineHeight: "52px", letterSpacing: "0.01em", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "40px", letterSpacing: "0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "28px", letterSpacing: "0.02em", fontWeight: "600" }],
        "title-base": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-caps": ["14px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" }],
      }
    },
  },
  plugins: [],
}
