/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#e2e8f0",
        "on-error-container": "#410002",
        "on-secondary-fixed-variant": "#910030",
        "surface": "#ffffff",
        "secondary": "#e11d48",
        "on-tertiary-fixed": "#002022",
        "tertiary-fixed": "#0284c7",
        "on-secondary-container": "#ffffff",
        "surface-container-high": "#e2e8f0",
        "surface-variant": "#e2e8f0",
        "primary": "#0f172a",
        "surface-tint": "#16a34a",
        "surface-container": "#f1f5f9",
        "tertiary-fixed-dim": "#0369a1",
        "surface-dim": "#f8fafc",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-surface": "#0f172a",
        "tertiary-container": "#e0f2fe",
        "tertiary": "#0284c7",
        "on-background": "#0f172a",
        "on-surface-variant": "#64748b",
        "secondary-fixed": "#e11d48",
        "inverse-primary": "#4ade80",
        "secondary-fixed-dim": "#be123c",
        "on-secondary-fixed": "#ffffff",
        "on-primary-fixed": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#0369a1",
        "inverse-on-surface": "#ffffff",
        "on-primary-container": "#14532d",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#ffffff",
        "on-surface": "#1e293b",
        "surface-container-highest": "#cbd5e1",
        "error-container": "#fee2e2",
        "secondary-container": "#e11d48",
        "error": "#dc2626",
        "surface-bright": "#ffffff",
        "primary-fixed-dim": "#15803d",
        "background": "#ffffff",
        "primary-fixed": "#16a34a",
        "outline": "#94a3b8",
        "primary-container": "#dcfce7",
        "surface-container-low": "#ffffff",
        "on-tertiary-fixed-variant": "#075985",
        "on-tertiary": "#ffffff",
        "brand-volt": "#16a34a",
        "brand-volt-dark": "#15803d",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "space-3xs": "0.125rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "margin-mobile": "1rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
      },
      fontFamily: {
        "headline-xl-mobile": ["Barlow Condensed", "sans-serif"],
        "headline-md": ["Barlow Condensed", "sans-serif"],
        "display-hero-mobile": ["Barlow Condensed", "sans-serif"],
        "title-base": ["Chivo", "sans-serif"],
        "headline-lg": ["Barlow Condensed", "sans-serif"],
        "body-md": ["Chivo", "sans-serif"],
        "headline-xl": ["Barlow Condensed", "sans-serif"],
        "body-lg": ["Chivo", "sans-serif"],
        "display-hero": ["Barlow Condensed", "sans-serif"],
        "label-sm": ["Chivo", "sans-serif"],
        "body-sm": ["Chivo", "sans-serif"],
        "label-caps": ["Barlow Condensed", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["72px", { lineHeight: "76px", letterSpacing: "0.02em", fontWeight: "800" }],
        "headline-xl": ["48px", { lineHeight: "52px", letterSpacing: "0.01em", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "40px", letterSpacing: "0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "28px", letterSpacing: "0.02em", fontWeight: "600" }],
        "title-base": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-caps": ["14px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" }],
      }
    },
  },
  plugins: [],
}
